// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError = { "type": "Database", "message": string } | { "type": "Validation", "message": string } | { "type": "NotFound", "message": string } | { "type": "Internal", "message": string } | { "type": "Etabs", "message": string };
